[theme]
base = "dark"
backgroundColor = "#070809"
secondaryBackgroundColor = "#0d0f12"
textColor = "#dde3ea"
font = "monospace"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = false
toolbarMode = "minimal"
